# Generated by Django 5.2 on 2025-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_medical_condition_pill_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='observations',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='insurance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labtechnician',
            name='certification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labtechnician',
            name='insurance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='labtechnician',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medical_condition',
            name='condition_description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='insurance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='pill_description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='concentration',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pill_count',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
